### ISSUE TITLE
examples/minimal.py not working with rich-click 1.8.*

### ISSUE THREAD

**Issue by rpadn** [betaboon/aio-microservice#27]
Updating `rich-click` to 1.8.1 prints the following when running `examples/minimal.py`:
```
$ pdm run examples/minimal.py run
2024-05-13 15:51:10.471 | INFO     | aio_microservice.core.service:run:240 - Starting Service: MyService
2024-05-13 15:51:10.471 | INFO     | aio_microservice.core.service:run:241 - Using Settings: debug=False http=HttpSettings(host='localhost', port=8080, timeout_keep_alive=5, cors=HttpCorsSettings(allow_origins='*', allow_methods='*', allow_headers='*', allow_credentials=False, allow_origin_regex=None, expose_headers='', max_age=600))
2024-05-13 15:51:10.498 | INFO     | uvicorn.server:serve:77 - Started server process [60133]
2024-05-13 15:51:10.498 | INFO     | uvicorn.lifespan.on:startup:46 - Waiting for application startup.
2024-05-13 15:51:10.504 | ERROR    | uvicorn.lifespan.on:send:121 - Traceback (most recent call last):
  File "/home/rpadn/dev/aio-microservice/.venv/lib/python3.12/site-packages/litestar/app.py", line 604, in lifespan
    await self._call_lifespan_hook(hook)
  File "/home/rpadn/dev/aio-microservice/.venv/lib/python3.12/site-packages/litestar/app.py", line 581, in _call_lifespan_hook
    await ret
  File "/home/rpadn/dev/aio-microservice/aio_microservice/core/service.py", line 224, in _emit_startup_message
    console = rich.console.Console()
              ^^^^^^^^^^^^
AttributeError: module 'rich' has no attribute 'console'. Did you mean: '_console'?

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/home/rpadn/dev/aio-microservice/.venv/lib/python3.12/site-packages/litestar/_asgi/asgi_router.py", line 167, in lifespan
  |     async with self.app.lifespan():
  |   File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
  |     return await anext(self.gen)
  |            ^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/rpadn/dev/aio-microservice/.venv/lib/python3.12/site-packages/litestar/app.py", line 592, in lifespan
  |     async with AsyncExitStack() as exit_stack:
  |   File "/usr/lib/python3.12/contextlib.py", line 754, in __aexit__
  |     raise exc_details[1]
  |   File "/usr/lib/python3.12/contextlib.py", line 737, in __aexit__
  |     cb_suppress = await cb(*exc_details)
  |                   ^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/rpadn/dev/aio-microservice/.venv/lib/python3.12/site-packages/litestar/events/emitter.py", line 111, in __aexit__
  |     await self._exit_stack.__aexit__(exc_type, exc_val, exc_tb)
  |   File "/usr/lib/python3.12/contextlib.py", line 754, in __aexit__
  |     raise exc_details[1]
  |   File "/usr/lib/python3.12/contextlib.py", line 737, in __aexit__
  |     cb_suppress = await cb(*exc_details)
  |                   ^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/rpadn/dev/aio-microservice/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/rpadn/dev/aio-microservice/.venv/lib/python3.12/site-packages/litestar/app.py", line 604, in lifespan
    |     await self._call_lifespan_hook(hook)
    |   File "/home/rpadn/dev/aio-microservice/.venv/lib/python3.12/site-packages/litestar/app.py", line 581, in _call_lifespan_hook
    |     await ret
    |   File "/home/rpadn/dev/aio-microservice/aio_microservice/core/service.py", line 224, in _emit_startup_message
    |     console = rich.console.Console()
    |               ^^^^^^^^^^^^
    | AttributeError: module 'rich' has no attribute 'console'. Did you mean: '_console'?
    +------------------------------------

2024-05-13 15:51:10.504 | ERROR    | uvicorn.lifespan.on:startup:57 - Application startup failed. Exiting.
```

Pinning `rich-click` to 1.7.* makes this work.
